apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME  # Dynamically replaced
spec:
  replicas: 2
  selector:
    matchLabels:
      app: $APP_NAME  # Dynamically replaced
  template:
    metadata:
      labels:
        app: $APP_NAME  # Dynamically replaced
    spec:
      containers:
        - name: $APP_NAME  # Dynamically replaced
          image: ${DOCKER_IMAGE}:latest  # Dynamic Docker image
          ports:
            - containerPort: 8080
