apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-go-gopher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-go-gopher
  template:
    metadata:
      labels:
        app: my-go-gopher
        test: biscuit-basket
    spec:
      containers:
        - name: my-go-gopher
          image: esketch545/my-go-gopher:sha-65c297bab1eafe1ff9b6685dcd30bb7a80720944
          ports:
            - containerPort: 8080