apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-go-gopher  # Replaced $APP_NAME with 'my-go-gopher'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-go-gopher  # Replaced $APP_NAME with 'my-go-gopher'
  template:
    metadata:
      labels:
        app: my-go-gopher  # Replaced $APP_NAME with 'my-go-gopher'
    spec:
      containers:
        - name: my-go-gopher  # Replaced $APP_NAME with 'my-go-gopher'
          image: esketch545/my-go-gopher:latest
          ports:
            - containerPort: 8080
