apiVersion: v1
kind: Service
metadata:
  name: my-go-gopher-service  # Replaced $APP_NAME with 'my-go-gopher-service'
spec:
  selector:
    app: my-go-gopher  # Replaced $APP_NAME with 'my-go-gopher'
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
