apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME-service  # Dynamically replaced
spec:
  selector:
    app: $APP_NAME  # Dynamically replaced
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
