name: Build, Push, and Trigger ArgoCD

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write
env:
  ACTIONS_STEP_DEBUG: true
  ACTIONS_RUNNER_DEBUG: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=sha-${{ github.sha }}
          docker build -t $DOCKER_IMAGE:$IMAGE_TAG .
          docker push $DOCKER_IMAGE:$IMAGE_TAG
        env:
          DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}

      - name: Update deployment YAML with new image and push changes to repository
        run: |
          IMAGE_TAG=sha-${{ github.sha }}
          sed -i "s|image:.*|image: $DOCKER_IMAGE:$IMAGE_TAG|g" k8s/deployment.yml
      
          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub Actions"
          
          git remote set-url origin https://github.com/${{ github.repository }}.git
          git add k8s/deployment.yml
          git commit -m "Update image to $IMAGE_TAG [skip ci]" || echo "No changes to commit"
          
          echo "Repository: ${{ github.repository }}"

          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main