name: Build and Push Docker Image

on:
    push:
      branches:
        - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      APP_NAME: my-go-gopher  # Define app name as a variable
      DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t $DOCKER_IMAGE:latest .
          docker push $DOCKER_IMAGE:latest

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up kubectl
        env:
          GKE_CLUSTER: ${{ vars.GKE_CLUSTER }}
          GKE_ZONE: ${{ vars.GKE_ZONE }}
          GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $GCP_PROJECT_ID

      - name: Replace placeholders in Kubernetes manifests
        run: |
          envsubst < k8s/deployment.yml > k8s/deployment-rendered.yml
          envsubst < k8s/service.yml > k8s/service-rendered.yml

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/deployment-rendered.yml
          kubectl apply -f k8s/service-rendered.yml
